### ISSUE TITLE
[ENH] Implement middleware of access mode management

### ISSUE THREAD

**Issue by NenetteGit** [Burger-api/burger-api#5]
**Describe the solution you'd like**
Modes:

- [x] Customers: 
    - [x] Can see the products, menus, and promotions. 
    - [x] Can order either connected or not.
- [x] Preparator: 
    - [x] Can see the orders and treat them. 
    - [x] He must be connected to realize those actions.
- [x] Admin: 
    - [x] Can manage products, menus, promotions and orders. 
    - [x] He must be connected.
    - [x] Edit user rights.

**Describe alternatives you've considered**
This must be realized into middlewares.

**Comment by Simonpo95** [comment]
Waiting for definitive routes to be updated in order to apply status verification
